/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import ProjetoPontoEletronico.Funcionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Pichau
 */
public class RegistraFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form RegistraFuncionario
     */
    public RegistraFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeCadastro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cpfCadastro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        funcaoCadastro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nascimentoCadastro = new com.toedter.calendar.JDateChooser();
        Cadastrar = new javax.swing.JButton();
        SairAdmin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        início = new javax.swing.JButton();
        HistPonto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        setResizable(false);

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("CPF:");

        cpfCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfCadastroActionPerformed(evt);
            }
        });

        jLabel3.setText("Função:");

        jLabel4.setText("Data de Nascimento:");

        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/application_add.png"))); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        SairAdmin.setText("Sair");
        SairAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairAdminActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/application_form_magnify.png"))); // NOI18N
        jButton1.setText("Histórico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        início.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/application_home.png"))); // NOI18N
        início.setText("Início");
        início.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inícioActionPerformed(evt);
            }
        });

        HistPonto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/application_form_magnify.png"))); // NOI18N
        HistPonto.setText("Hist. Ponto");
        HistPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistPontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nascimentoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(funcaoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(cpfCadastro)
                            .addComponent(nomeCadastro)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Cadastrar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(SairAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(HistPonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(início, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funcaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nascimentoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar)
                    .addComponent(jButton1)
                    .addComponent(início)
                    .addComponent(HistPonto))
                .addGap(18, 18, 18)
                .addComponent(SairAdmin)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cpfCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfCadastroActionPerformed

    private void SairAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairAdminActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SairAdminActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        String getNome = nomeCadastro.getText();
        String getCpf =  cpfCadastro.getText();
        String getFuncao = funcaoCadastro.getText();
        String getNascimento = ((JTextField)nascimentoCadastro.getDateEditor().getUiComponent()).getText();
        
        arrayHistorico.add(new Funcionario(getNome, getCpf, getFuncao, getNascimento));
        
        //Historico historico = new Historico();
        //historico.updateTable(arrayHistorico);
        //historico.setVisible(true);
        
        JOptionPane.showMessageDialog(this, "Funcionário "+ getNome + " cadastrado com sucesso!");
    }//GEN-LAST:event_CadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Historico historico = new Historico();
        historico.updateTable(arrayHistorico);
        historico.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inícioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inícioActionPerformed
        // TODO add your handling code here:
        new Ponto().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inícioActionPerformed

    private void HistPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistPontoActionPerformed
        // TODO add your handling code here:
        HistoricoPonto ponto = new HistoricoPonto();
        ponto.updateTable2(arrayPonto);
        ponto.setVisible(true);
        //new HistoricoPonto().setVisible(true);
    }//GEN-LAST:event_HistPontoActionPerformed

    public static ArrayList<Funcionario> arrayHistorico = new ArrayList<>();
    public static ArrayList<Funcionario> arrayPonto = new ArrayList<>();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistraFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistraFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistraFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistraFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistraFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton HistPonto;
    private javax.swing.JButton SairAdmin;
    private javax.swing.JTextField cpfCadastro;
    private javax.swing.JTextField funcaoCadastro;
    private javax.swing.JButton início;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser nascimentoCadastro;
    private javax.swing.JTextField nomeCadastro;
    // End of variables declaration//GEN-END:variables
}
